name: preflight_project
services:
  postgres:
    image: postgres:16-alpine
    container_name: db
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - pf-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  backend:
    container_name: backend
    build: .
    ports:
      - ${PORT}:3000
    networks:
      - preflight_pf-net
    environment:
      - DATABASE_DSN=${DATABASE_DSN}
networks:
  preflight_pf-net: # Check by using `docker network ls` command
    external: true
volumes:
  pf-data: