name: preflight_project
services:
  postgres:
    image: postgres:16-alpine
    container_name: db
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - pf-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  backend:
    container_name: backend
    build: .
    ports:
      - ${PORT}:3000
    environment:
      - DATABASE_DSN=${DATABASE_DSN}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
    depends_on:
      - postgres
    image: jirayu1004za/preflight_project-backend:latest
networks:
  preflight_pf-net: # Check by using `docker network ls` command
    external: true
volumes:
  pf-data: